# docker-compose config

version: '2'
services:
  database:
    env_file: .env
    ports:
      - "5432:5432"
    build:
      context: ./database/
    restart: always

  server:
    env_file: .env
    build:
      context: ./server/
    ports:
      - "8080:8080"
    depends_on:
      - database
    links:
      - "database:${DBHOST}"

  client:
    build:
      context: ./client/
    ports:
      - "3000:3000"
    depends_on:
      - server
    links:
      - "server:server"